import urllib.request
r = urllib.request.urlopen('http://localhost:8765/')
html = r.read().decode()
print(f'Page loaded: {len(html)} bytes')
print(f'Has sidebar: {"sidebar" in html}')
print(f'Has model tabs: {"model-tab" in html}')
print(f'Has marked.js: {"marked" in html}')
print(f'Has highlight.js: {"highlight" in html}')
print(f'Has sendChat: {"sendChat" in html}')
print(f'Has startPodcast: {"startPodcast" in html}')
print(f'Has slide-panel: {"slide-panel" in html}')
